### ISSUE TITLE
OpenX API consumer key and secret

### ISSUE THREAD

**Issue by narektorosyan** [mausch/OpenX.Net#10]
I'm trying to use OpnenX API, but I can't retrieve consumer key and consumer secret. If anyone already works with OpenX API, please help

**Comment by mausch** [comment]
I haven't used this for years, but I see that the open source OpenX server product is now http://www.revive-adserver.com/ . Have you looked into its documentation?

**Comment by narektorosyan** [comment]
I have found that the customer key and secret are the same for all users on market instances, which you are able to get from OpenX support.
Thanks for attention.
